### PR TITLE
Remove the use of NIO from WebSocket code

### PR DESCRIPTION
**Pull request by om26er**
This branch is not ready, though its in a working state, the EchoClient works, though currently we are not handling fragmentation, this is being worked on.

Its mostly a request for comments at this stage.

Below are some things that I know are bad and I am working on them:
- processHandshake() should be moved back to processData() as it previously was and as it is in other autobahn implementations.
- The http status parsing code should be moved back to parseHttpStatus() from processHandshake, again due to similar reasons.
- Remove commented code.
- Add code comments, where applicable.
- ...and more.

### CODE REVIEW

**Comment by om26er** [comment]
One reason the diff might look funny is because in some files tab size of this project was 3 spaces, in others 4, so that was conflicting a bit with my editor. Will also do another PR to make that uniform everywhere, but later.

**Comment by oberstet** [comment]
Awesome! Thanks for your work! Collaboration is starting good=)

Cleaning up the tabs mess: +1

Rgd testing the WebSocket layer: guess you are aware of https://github.com/crossbario/autobahn-testsuite ?

In the end, this should pass 100% green (without the tests for websocket-compression probably, because this is completely unimplemented in AB-Android right now). It did pass 100% green in the past - and it also does test fragmentation and all kinds of corner cases. Just mentioning here so you are aware.

Sidenote: I have an issue https://github.com/crossbario/crossbar-docker/issues/13 to simplify usage of AB testsuite also using a Docker image. Let me know if that would simplify things for you, then I can do that. Easy.

**Comment by om26er** [comment]
> Rgd testing the WebSocket layer: guess you are aware of https://github.com/crossbario/autobahn-testsuite ?

I was aware of the autobahn-testsuite, its famous ;) but in current context, I hadn't looked into it.

> In the end, this should pass 100% green (without the tests for websocket-compression probably, because this is completely unimplemented in AB-Android right now). It did pass 100% green in the past - and it also does test fragmentation and all kinds of corner cases. Just mentioning here so you are aware.

I didn't know if the current implementation was passing that suite, though I presume we won't be getting a 100% pass rate today, will first run tests for the fuzzing client and see the pass rate on master. So that I have a baseline success rate for this pull request.

> Sidenote: I have an issue crossbario/crossbar-docker#13 to simplify usage of AB testsuite also using a Docker image. Let me know if that would simplify things for you, then I can do that. Easy.

Wrote there, but yep, that will indeed make things simpler.

**Comment by om26er** [comment]
Ok, so this branch got bigger than I anticipated. There was some offset issue that took me a while to figure but now we are at least able to run some autobahn tests.

Though it seems performance is quite slow than previous implementation using NIO so that is something to fix. Currently I am reading the raw InputStream instead of using a buffered stream, also the data array is being recreated (very inefficient), so these are things that I plan to fix in next iteration, instead of making this branch even bigger.

Once this lands, the 4 space tabs and Dockerfile branches are incoming.

**Comment by om26er** [comment]
Updated the title as I believe we can now consider this for landing.

On a slightly different note: The copyright header still refers to tavendo. @oberstet what are your thoughts on updating the copyright header, shall it be done in one go or slowly as we go forward ?

**Comment by oberstet** [comment]
@om26er rgd copyright header: good point! we should change that in one go over all files to the following:

```java
///////////////////////////////////////////////////////////////////////////////
//
//  AutobahnJava
//
//  Copyright (c) Crossbar.io Technologies GmbH and contributors
//
//  Licensed under the MIT License.
//  http://www.opensource.org/licenses/mit-license.php
//
///////////////////////////////////////////////////////////////////////////////
```

**Comment by om26er** [comment]
Thanks for merging this.

I have been profiling the performance and blame the recreation of the buffer that holds the data (I wrote that). The latest commits(already merged) in this branch make use of BufferedInputStream, that improves the performance a bit but the real fix is in maintaining a single buffer and seeking through it, instead of recreating it. Now that this PR is merged, I'll do that in another one.

**Comment by oberstet** [comment]
@om26er sounds good! thanks for your work! I'll try to prioritize creating a Docker image for the AB testsuite .. in days.

**Pull request merged**
