### PR TITLE
Start using gradle as build system, create a demo-gallery app.

### PR DESCRIPTION
**Pull request by om26er**
A preliminary change to the project, porting to gradle has allowed me to do the the development on Android studio, resulting in easy debugging. Highlights of this PR:
- Move the project to Gradle.
- Create a demo-gallery Android client, currently it only opens EchoClient.
- Delete jackson-core and jackson-mapper jar files as they are downloaded by gradle automatically.

TODO:
- Update the README on how to build and run the project.
-   Create a docker container with Android toolchain.
-   Create a script that builds and pulls automatically.

Note: I had to update the minimum Android version requirements to API level 10 (aka 2.3) because it seems latest support libraries have a conflict with Android 2.2

### CODE REVIEW

**Comment by oberstet** [comment]
Two quick comments:

* the new vendor prefix should be `io/crossbar/autobahn` rather than `de/tavendo/autobahn`
* the minimum API level should be 24 (unless/until we add a polyfill for that)

**Comment by om26er** [comment]
When I was working on this branch, I did think of using crossbar as vendor but deferred that with the thought to do it later, everywhere. But you are right, I will update this branch to use io.crossbar.autobahn as package name tomorrow.

It may make more sense to update the minimum API level at a later date, when we actually have some code that requires a specific API level. Currently even my device is on API level 18, which I am using for testing.

To be able to actually test this PR and to ensure both the Android apk of the demo-gallery and the library are being build, I put together a set of commands to pull and build this project, including installation of the Android Sdk.

```
apt update; apt install libc6-dev-i386 lib32z1 unzip default-jdk-headless wget expect git -y; wget https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip; unzip sdk-tools-linux-3859397.zip; /usr/bin/expect -c 'spawn tools/bin/sdkmanager "platforms;android-25" "build-tools;25.0.2"' -c 'expect Accept*' -c 'send y\r' -c 'interact'; git clone https://github.com/om26er/autobahn-android.git -b abjv2; cd autobahn-android; ANDROID_HOME=$OLDPWD ./gradlew assemble; cd -
```

I have been using that mini script in a LXD container running Ubuntu 16.04. Will look into creating a docker container from that tomorrow.

**Comment by om26er** [comment]
Pushed the change that changes package name for the demo-gallery. For the library I will do the change in a separate branch.

Overall this change is pretty safe(tm), apart from moving some directories around, the actual library code is untouched.

**Comment by oberstet** [comment]
> It may make more sense to update the minimum API level at a later date

Ok, makes sense.

So should I merge this PR or do you want it to keep open to accumulate more?

**Comment by om26er** [comment]
Please merge this, I have the NIO removal branch that is stacked on top of this, so if we land this branch, it will clear the path for that one.

**Pull request merged**
